# This workflow will run CICD agains Azure using Terragrunt/Terraform.
name: Azure CICD Workflow

on:
  # Manual workflow
  workflow_dispatch:

# Permissions for the workflow
permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

# Environment variables for Azure authentication using OIDC. These will be used by the Azure Login action and Terragrunt/Terraform.
env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_USE_MSI: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # - name: Azure Login
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Validate
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_dir: 'environments/dev/spaincentral'
        tg_command: 'stack run validate'
    
    - name: Unlock
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_dir: 'environments/dev/spaincentral/networking'
        tg_command: 'run force-unlock -- -force e24dea4c-c178-0f05-c4f2-d8301ec174a0'

    # - name: Plan
    #   uses: gruntwork-io/terragrunt-action@v3
    #   with:
    #     tg_dir: 'environments/dev/spaincentral'
    #     tg_command: 'stack run plan'
