# This workflow will run CICD agains Azure using Terragrunt/Terraform.
name: Azure CICD Workflow

on:
  # Manual workflow
  workflow_dispatch:

# Permissions for the workflow
permissions:
  contents: read
  id-token: write  # Required for OIDC authentication

# Environment variables for Azure authentication using OIDC. These will be used by the Azure Login action and Terragrunt/Terraform.
env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_USE_OIDC: true
    
jobs:
  validate-and-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Clean
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_dir: 'environments/dev/spaincentral'
        tg_command: 'stack clean'

    - name: Validate
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_dir: 'environments/dev/spaincentral'
        tg_command: 'stack run validate'
    
    - name: Plan
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_dir: 'environments/dev/spaincentral'
        tg_command: 'stack run plan -- -out=tfplan'
    
    - name: Upload plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: environments/dev/spaincentral/tfplan
        retention-days: 1
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: dev
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
    
  #   - name: Deploy
  #     uses: gruntwork-io/terragrunt-action@v3
  #     with:
  #       tg_dir: 'environments/dev/spaincentral'
  #       tg_command: 'stack run apply'

